package twofactor

import (
	"strings"
	"testing"
	"time"

	"github.com/pquerna/otp"
	"github.com/pquerna/otp/totp"
)

// codeAt produces the code an authenticator app would show at t, which is what
// lets these tests exercise drift and expiry without waiting for real seconds
// to pass.
func codeAt(t *testing.T, secret string, at time.Time, opts Options) string {
	t.Helper()

	opts = opts.withDefaults()
	code, err := totp.GenerateCodeCustom(secret, at.UTC(), totp.ValidateOpts{
		Period:    opts.periodSeconds(),
		Skew:      uint(opts.Skew),
		Digits:    opts.digits(),
		Algorithm: otp.AlgorithmSHA1,
	})
	if err != nil {
		t.Fatalf("generate a code: %v", err)
	}
	return code
}

func newSecret(t *testing.T) Secret {
	t.Helper()

	secret, err := NewSecret("alice@example.com", Options{Issuer: "Ryla"})
	if err != nil {
		t.Fatalf("NewSecret: %v", err)
	}
	return secret
}

// TestTheCurrentCodeIsAccepted is the whole feature working: the code the app
// is showing right now signs the user in. Everything else here is about what
// must not be accepted.
func TestTheCurrentCodeIsAccepted(t *testing.T) {
	secret := newSecret(t)
	now := time.Now()

	if !VerifyAt(secret.Base32, codeAt(t, secret.Base32, now, Options{}), now, Options{}) {
		t.Fatal("the code being shown right now was rejected")
	}
}

// TestAStaleCodeIsRejected protects the property that makes TOTP worth using: a
// code seen over a shoulder, read off a screenshot, or captured by a phishing
// page is worthless a couple of minutes later. A window that quietly grew would
// still pass every other test in this file.
func TestAStaleCodeIsRejected(t *testing.T) {
	secret := newSecret(t)
	now := time.Now()

	// Five minutes is ten periods; the skew tolerance is one.
	stale := codeAt(t, secret.Base32, now.Add(-5*time.Minute), Options{})

	if VerifyAt(secret.Base32, stale, now, Options{}) {
		t.Fatal("a code from five minutes ago was accepted")
	}
}

// TestClockDriftOfOnePeriodIsTolerated covers the other half of the window. A
// phone whose clock is half a minute out is common enough that refusing it
// would make the feature look broken, and one period is as far as RFC 6238
// suggests going.
func TestClockDriftOfOnePeriodIsTolerated(t *testing.T) {
	secret := newSecret(t)
	now := time.Now()

	for name, at := range map[string]time.Time{
		"a period behind": now.Add(-DefaultPeriod),
		"a period ahead":  now.Add(DefaultPeriod),
	} {
		code := codeAt(t, secret.Base32, at, Options{})
		if !VerifyAt(secret.Base32, code, now, Options{}) {
			t.Errorf("a code generated by a clock %s was rejected", name)
		}
	}
}

// TestTwoPeriodsOfDriftIsTooFar pins the edge of the window. Without this the
// tolerance could be widened by a factor of ten and nothing would complain.
func TestTwoPeriodsOfDriftIsTooFar(t *testing.T) {
	secret := newSecret(t)
	now := time.Now()

	code := codeAt(t, secret.Base32, now.Add(-2*DefaultPeriod), Options{})
	if VerifyAt(secret.Base32, code, now, Options{}) {
		t.Fatal("a code two periods old was accepted")
	}
}

// TestACodeFromAnotherSecretIsRejected is the property that keeps one enrolment
// from opening another account.
func TestACodeFromAnotherSecretIsRejected(t *testing.T) {
	mine, theirs := newSecret(t), newSecret(t)
	now := time.Now()

	if VerifyAt(mine.Base32, codeAt(t, theirs.Base32, now, Options{}), now, Options{}) {
		t.Fatal("a code generated from a different secret was accepted")
	}
}

// TestSpacesInACodeAreIgnored covers the ordinary case of a code copied out of
// an authenticator app, which pastes it as "123 456".
func TestSpacesInACodeAreIgnored(t *testing.T) {
	secret := newSecret(t)
	now := time.Now()

	code := codeAt(t, secret.Base32, now, Options{})
	spaced := code[:3] + " " + code[3:]

	if !VerifyAt(secret.Base32, spaced, now, Options{}) {
		t.Fatalf("the code %q was rejected once pasted as %q", code, spaced)
	}
}

func TestEmptyAndMalformedInputAreRejected(t *testing.T) {
	secret := newSecret(t)
	now := time.Now()

	cases := map[string]struct{ secret, code string }{
		"no code":         {secret.Base32, ""},
		"letters":         {secret.Base32, "abcdef"},
		"no secret":       {"", codeAt(t, secret.Base32, now, Options{})},
		"unusable secret": {"not base32 at all!", "123456"},
	}

	for name, tc := range cases {
		if VerifyAt(tc.secret, tc.code, now, Options{}) {
			t.Errorf("%s: accepted", name)
		}
	}
}

// TestTheURIIdentifiesTheAccountAndTheIssuer protects what the user sees. A URI
// missing the issuer produces an entry in the authenticator app that says
// nothing about which site it belongs to, and somebody with six of those cannot
// tell them apart.
func TestTheURIIdentifiesTheAccountAndTheIssuer(t *testing.T) {
	secret, err := NewSecret("alice@example.com", Options{Issuer: "Ryla"})
	if err != nil {
		t.Fatalf("NewSecret: %v", err)
	}

	if !strings.HasPrefix(secret.URI, "otpauth://totp/") {
		t.Errorf("URI = %q, which is not an otpauth TOTP URI", secret.URI)
	}

	key, err := otp.NewKeyFromURL(secret.URI)
	if err != nil {
		t.Fatalf("the generated URI does not parse: %v", err)
	}
	if key.Issuer() != "Ryla" {
		t.Errorf("issuer = %q, want Ryla", key.Issuer())
	}
	if key.AccountName() != "alice@example.com" {
		t.Errorf("account = %q, want alice@example.com", key.AccountName())
	}
	if key.Secret() != secret.Base32 {
		t.Error("the URI carries a different secret from the one returned")
	}
}

// TestSecretsAreNotReused is the one thing a generator must never get wrong.
func TestSecretsAreNotReused(t *testing.T) {
	seen := map[string]bool{}
	for range 32 {
		secret := newSecret(t)
		if seen[secret.Base32] {
			t.Fatalf("the same secret was generated twice: %q", secret.Base32)
		}
		seen[secret.Base32] = true
	}
}

func TestNewSecretRefusesToProduceAnUnlabelledEntry(t *testing.T) {
	if _, err := NewSecret("alice@example.com", Options{}); err == nil {
		t.Error("a secret with no issuer was generated")
	}
	if _, err := NewSecret("  ", Options{Issuer: "Ryla"}); err == nil {
		t.Error("a secret with no account name was generated")
	}
}

func TestQRCodeIsAPNGOfTheURI(t *testing.T) {
	secret := newSecret(t)

	img, err := QRCodePNG(secret.URI, 200)
	if err != nil {
		t.Fatalf("QRCodePNG: %v", err)
	}
	if !strings.HasPrefix(string(img), "\x89PNG") {
		t.Error("the QR code is not a PNG")
	}

	if _, err := QRCodePNG("not a uri", 200); err == nil {
		t.Error("a QR code was rendered from something that is not an otpauth URI")
	}
}

// TestURIRebuildsTheSameEnrolment matters because the URI is deliberately not
// stored: it contains the secret, so keeping it would mean keeping a second,
// unsealed copy. Rebuilding it has to produce the same enrolment the user
// already scanned, or the QR code on a refreshed page would silently enrol a
// different secret from the one about to be confirmed.
func TestURIRebuildsTheSameEnrolment(t *testing.T) {
	secret := newSecret(t)

	rebuilt, err := URI("alice@example.com", secret.Base32, Options{Issuer: "Ryla"})
	if err != nil {
		t.Fatalf("URI: %v", err)
	}

	key, err := otp.NewKeyFromURL(rebuilt)
	if err != nil {
		t.Fatalf("the rebuilt URI does not parse: %v", err)
	}
	if key.Secret() != secret.Base32 {
		t.Fatalf("rebuilt secret = %q, want %q", key.Secret(), secret.Base32)
	}

	// Lower case and stray spaces, as a secret typed back in by hand arrives.
	spaced, err := URI("alice@example.com", " "+strings.ToLower(secret.Base32)+" ", Options{Issuer: "Ryla"})
	if err != nil {
		t.Fatalf("URI with a hand-typed secret: %v", err)
	}
	if spaced != rebuilt {
		t.Error("a hand-typed secret rebuilt a different URI")
	}
}

func TestURIRefusesAnUnusableSecret(t *testing.T) {
	if _, err := URI("alice@example.com", "not base32 at all!", Options{Issuer: "Ryla"}); err == nil {
		t.Error("a URI was built from something that is not a base32 secret")
	}
	if _, err := URI("alice@example.com", "JBSWY3DPEHPK3PXP", Options{}); err == nil {
		t.Error("a URI was built with no issuer")
	}
}
